In [5]:
# Import the libraries

import pandas as pd
from bokeh.plotting import figure, output_file, show

In [6]:
def make_dashboard(x, gdp_change, unemployment, title, file_name):
    output_file(file_name)
    p = figure(title=title, x_axis_label='year', y_axis_label='%')
    p.line(x.squeeze(), gdp_change.squeeze(), color="firebrick", line_width=4, legend="% GDP change")
    p.line(x.squeeze(), unemployment.squeeze(), line_width=4, legend="% unemployed")
    show(p)

In [7]:

links={'GDP':'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv',\
       'unemployment':'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'}

In [8]:
#Creating Data frame ot capture the GDP

df_gdp_us = pd.read_csv(links["GDP"])
df_gdp_us.head()

print(df_gdp_us)
df_gdp_us.head()

    date  level-current  level-chained  change-current  change-chained
0   1948          274.8         2020.0            -0.7            -0.6
1   1949          272.8         2008.9            10.0             8.7
2   1950          300.2         2184.0            15.7             8.0
3   1951          347.3         2360.0             5.9             4.1
4   1952          367.7         2456.1             6.0             4.7
5   1953          389.7         2571.4             0.3            -0.6
6   1954          391.1         2556.9             8.9             7.1
7   1955          426.2         2739.0             5.6             2.1
8   1956          450.1         2797.4             5.5             2.1
9   1957          474.9         2856.3             1.5            -0.7
10  1958          482.0         2835.3             8.4             6.9
11  1959          522.5         3031.0             4.0             2.6
12  1960          543.3         3108.7             3.7             2.6
13  1961          563.3         3188.1             7.4             6.1
14  1962          605.1         3383.1             5.6             4.4
15  1963          638.6         3530.4             7.4             5.8
16  1964          685.8         3734.0             8.4             6.5
17  1965          743.7         3976.7             9.6             6.6
18  1966          815.0         4238.9             5.7             2.7
19  1967          861.7         4355.2             9.4             4.9
20  1968          942.5         4569.0             8.2             3.1
21  1969         1019.9         4712.5             5.5             0.2
22  1970         1075.9         4722.0             8.5             3.3
23  1971         1167.8         4877.6             9.8             5.3
24  1972         1282.4         5134.3            11.4             5.6
25  1973         1428.5         5424.1             8.4            -0.5
26  1974         1548.8         5396.0             9.0            -0.2
27  1975         1688.9         5385.4            11.2             5.4
28  1976         1877.6         5675.4            11.1             4.6
29  1977         2086.0         5937.0            13.0             5.5
..   ...            ...            ...             ...             ...
39  1987         4870.2         8132.6             7.9             4.2
40  1988         5252.6         8474.5             7.7             3.7
41  1989         5657.7         8786.4             5.7             1.9
42  1990         5979.6         8955.0             3.3            -0.1
43  1991         6174.0         8948.4             5.9             3.5
44  1992         6539.3         9266.6             5.2             2.8
45  1993         6878.7         9521.0             6.3             4.0
46  1994         7308.8         9905.4             4.8             2.7
47  1995         7664.1        10174.8             5.7             3.8
48  1996         8100.2        10561.0             6.2             4.4
49  1997         8608.5        11034.9             5.7             4.5
50  1998         9089.2        11525.9             6.3             4.8
51  1999         9660.6        12065.9             6.5             4.1
52  2000        10284.8        12559.7             3.2             1.0
53  2001        10621.8        12682.2             3.4             1.7
54  2002        10977.5        12908.8             4.8             2.9
55  2003        11510.7        13271.1             6.6             3.8
56  2004        12274.9        13773.5             6.7             3.5
57  2005        13093.7        14234.2             6.0             2.9
58  2006        13855.9        14613.8             4.6             1.9
59  2007        14477.6        14873.7             1.8            -0.1
60  2008        14718.6        14830.4            -1.8            -2.5
61  2009        14418.7        14418.7             3.8             2.6
62  2010        14964.4        14783.8             3.7             1.6
63  2011        15517.9        15020.6             4.2             2.2
64  2012        16155.3        15354.6             3.6             1.8
65  2013        16691.5        15612.2             4.4             2.5
66  2014        17427.6        16013.3             4.0             2.9
67  2015        18120.7        16471.5             2.7             1.6
68  2016        18624.5        16716.2             4.2             2.2

[69 rows x 5 columns]

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [9]:
df_unemp = pd.read_csv(links['unemployment'])
print (df_unemp)
df_unemp.head()

    date  unemployment
0   1948      3.750000
1   1949      6.050000
2   1950      5.208333
3   1951      3.283333
4   1952      3.025000
5   1953      2.925000
6   1954      5.591667
7   1955      4.366667
8   1956      4.125000
9   1957      4.300000
10  1958      6.841667
11  1959      5.450000
12  1960      5.541667
13  1961      6.691667
14  1962      5.566667
15  1963      5.641667
16  1964      5.158333
17  1965      4.508333
18  1966      3.791667
19  1967      3.841667
20  1968      3.558333
21  1969      3.491667
22  1970      4.983333
23  1971      5.950000
24  1972      5.600000
25  1973      4.858333
26  1974      5.641667
27  1975      8.475000
28  1976      7.700000
29  1977      7.050000
..   ...           ...
39  1987      6.175000
40  1988      5.491667
41  1989      5.258333
42  1990      5.616667
43  1991      6.850000
44  1992      7.491667
45  1993      6.908333
46  1994      6.100000
47  1995      5.591667
48  1996      5.408333
49  1997      4.941667
50  1998      4.500000
51  1999      4.216667
52  2000      3.966667
53  2001      4.741667
54  2002      5.783333
55  2003      5.991667
56  2004      5.541667
57  2005      5.083333
58  2006      4.608333
59  2007      4.616667
60  2008      5.800000
61  2009      9.283333
62  2010      9.608333
63  2011      8.933333
64  2012      8.075000
65  2013      7.358333
66  2014      6.158333
67  2015      5.275000
68  2016      4.875000

[69 rows x 2 columns]

   date  unemployment
0  1948      3.750000
1  1949      6.050000
2  1950      5.208333
3  1951      3.283333
4  1952      3.025000

In [10]:

df_unemp85 = df_unemp[df_unemp['unemployment'] > 8.5]
df_unemp85.head()

    date  unemployment
34  1982      9.708333
35  1983      9.600000
61  2009      9.283333
62  2010      9.608333
63  2011      8.933333

In [11]:
df_unemp85 = df_unemp[df_unemp['unemployment'] > 8.5]
df_unemp85.head()

    date  unemployment
34  1982      9.708333
35  1983      9.600000
61  2009      9.283333
62  2010      9.608333
63  2011      8.933333

In [12]:
# Create your dataframe with column date
x = df_gdp_us['date']
x.head()

0    1948
1    1949
2    1950
3    1951
4    1952
Name: date, dtype: int64

In [13]:
gdp_change = df_gdp_us['change-current'] # Create your dataframe with column change-current
gdp_change.head()

0    -0.7
1    10.0
2    15.7
3     5.9
4     6.0
Name: change-current, dtype: float64

In [14]:
unemployment = df_unemp['unemployment'] # Create your dataframe with column unemployment
unemployment.head()

0    3.750000
1    6.050000
2    5.208333
3    3.283333
4    3.025000
Name: unemployment, dtype: float64

In [15]:
title = 'GDP and Unemployment Data'# Give your dashboard a string title

In [16]:
file_name = "index.html"

In [17]:
# Fill up the parameters in the following function:
make_dashboard(x=x, gdp_change=gdp_change, unemployment= unemployment, title=title, file_name=file_name)

In [18]:
credentials = {

   "apikey": "your-api-key",

   "cos_hmac_keys": {

    "access_key_id": "your-access-key-here", 

     "secret_access_key": "your-secret-access-key-here"

   },

 
    "endpoints": "your-endpoints",

   "iam_apikey_description": "your-iam_apikey_description",

   "iam_apikey_name": "your-iam_apikey_name",

   "iam_role_crn": "your-iam_apikey_name",

    "iam_serviceid_crn": "your-iam_serviceid_crn",

  "resource_instance_id": "your-resource_instance_id"

}

In [52]:
 #@hidden_cell

In [53]:
# @hidden_cell
{
  "apikey": "WQ8FrlNzCyY_GqGDJ-YZUnhKIXY7OAK2gY3l0RAz_qhb",
  "cos_hmac_keys": {
    "access_key_id": "4c6f3bc1a72042f99e6955ceb5b542fc",
    "secret_access_key": "a2ff598a121e50c9d0f9f5d87851fba0277334e2d5cdc807"
  },
  "endpoints": "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
  "iam_apikey_description": "Auto-generated for key 4c6f3bc1-a720-42f9-9e69-55ceb5b542fc",
  "iam_apikey_name": "Service credentials-1",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/9135b6556a55433e87eeea2a5e3254b1::serviceid:ServiceId-01bd982f-075d-4cf2-a96a-8c8be4416ffd",
  "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/9135b6556a55433e87eeea2a5e3254b1:89eff647-f774-4d9b-a74c-1b814db79783::"
}

{'apikey': 'GQiXKjpQLZSLKsvWs8rnpqV7bf7p38Hf93HI9xRgFflu',
 'cos_hmac_keys': {'access_key_id': '100cf7a821f640f983dc0efc9d45691b',
  'secret_access_key': 'f933fa5d6201c4311cd1bc698f0eb10bdb3ee29ff2e4db19'},
 'endpoints': 'https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints',
 'iam_apikey_description': 'Auto-generated for key 100cf7a8-21f6-40f9-83dc-0efc9d45691b',
 'iam_apikey_name': 'WDP-Editor-courserajupyternotebook-donotdelete-pr-w8qedyjwnec7k5',
 'iam_role_crn': 'crn:v1:bluemix:public:iam::::serviceRole:Writer',
 'iam_serviceid_crn': 'crn:v1:bluemix:public:iam-identity::a/9135b6556a55433e87eeea2a5e3254b1::serviceid:ServiceId-bbbf9356-aa33-411d-abcd-eb288ce7dd3b',
 'resource_instance_id': 'crn:v1:bluemix:public:cloud-object-storage:global:a/9135b6556a55433e87eeea2a5e3254b1:89eff647-f774-4d9b-a74c-1b814db79783::'}

In [54]:
endpoint = 'https://s3-api.us-geo.objectstorage.softlayer.net'

In [55]:
bucket_name = 'courserajupyternotebook-donotdelete-pr-w8qedyjwnec7k5' # Type your bucket name on IBM Cloud

In [56]:
import boto3

In [57]:
resource = boto3.resource(
    's3',
    aws_access_key_id = credentials["cos_hmac_keys"]['access_key_id'],
    aws_secret_access_key = credentials["cos_hmac_keys"]["secret_access_key"],
    endpoint_url = endpoint,
)

In [58]:
import os

directory = os.getcwd()
html_path = directory + "/" + file_name

In [59]:
# Type your code here
f = open(html_path,'r')

In [60]:

# Fill up the parameters in the following function:
resource.Bucket(name=bucket_name).put_object(Key=file_name, Body=f.read())

ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key ID you provided does not exist in our records.

In [36]:
# Fill in the value for each key
Params = {'Bucket':bucket_name ,'Key':file_name }

In [37]:
import sys
time = 7*24*60**2
client = boto3.client(
    's3',
    aws_access_key_id = credentials["cos_hmac_keys"]['access_key_id'],
    aws_secret_access_key = credentials["cos_hmac_keys"]["secret_access_key"],
    endpoint_url=endpoint,

)
url = client.generate_presigned_url('get_object',Params=Params,ExpiresIn=time)
print(url)

https://s3-api.us-geo.objectstorage.softlayer.net/at-cc-tutorial/index.html?Expires=1560320484&AWSAccessKeyId=your-access-key-here&Signature=FrI94wPe%2BeasgwNelg8DHcg9%2FxE%3D